ctrl_interface=/var/run/wpa_supplicant
update_config=1

network={
	ssid="YOUR_WIFI_SSID_1"
	psk="YOUR_WIFI_PASSWORD_1"
	key_mgmt=WPA-PSK
	priority=10
}
network={
	ssid="YOUR_WIFI_SSID_2"
	psk="YOUR_WIFI_PASSWORD_2"
	key_mgmt=WPA-PSK
	priority=10
}
network={
	ssid="YOUR_WIFI_SSID_3"
	psk="YOUR_WIFI_PASSWORD_3"
	key_mgmt=WPA-PSK
	priority=10
}
network={
	ssid="YOUR_WIFI_SSID_4"
	psk="YOUR_WIFI_PASSWORD_4"
	key_mgmt=WPA-PSK
	priority=10
}





